language:
  elixir

matrix:
  include:
    - otp_release: 17.5
      elixir: 1.0.5
    - otp_release: 17.5
      elixir: 1.1.1
    - otp_release: 18.3
      elixir: 1.1.1
    - otp_release: 18.3
      elixir: 1.2.6
    - otp_release: 18.3
      elixir: 1.3.3
    - otp_release: 19.0
      elixir: 1.3.3

services:
  - redis-server

script:
  - mix test --trace
